spring:
    profiles:
        active:
        - dev

---

server:
  port: 9001

feign:
  hystrix:
    enabled: false

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

spring:
  profiles: dev #开发环境
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5