spring:
    profiles:
        active:
        - dev

---

server:
  port: 9527

spring:
  application:
    name: config-eureka-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true


info:
  app.name: config-eureka-zuul-gateway
  company.name: xiaoxiaoqiang

#zuul:
#  routes:
#    mydept.serviceId: microservicecloud-dept
#    mydept.path: /mydept/**
#这里的路由解释：mydept是自己定义的路由名称，而在这个路由下满足/mydept/** 映射的请求转发到microservicecloud-dept服务中
  #ignored-services: microservicecloud-dept
  #ignored-services: microservicecloud-dept
  #prefix: /atguigu
